name: flutter_appwrite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/appwrite
  appwrite: ^14.0.0
  # appwrite: ^13.1.1
  # https://pub.dev/packages/iconsax_flutter
  iconsax_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
